# Generated by Django 5.1.8 on 2025-04-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_trigger_scrape',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trigger_scrape',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Scrape Daily?'),
        ),
    ]
